const coreDataDetails = {
    availableDepartments: [
        "Oceans and Coastal Systems & Blue Economy Research",
        "Marine and Coastal Fisheries Research",
        "Oceanography and Hydrography Research",
        "Freshwater Systems Research",
        "Freshwater Fisheries Research",
        "Limnology Research",
        "Aquaculture Research",
        "Freshwater Aquaculture Research",
        "Mariculture Research",
        "Socioeconomic Assessment and Monitoring",
        "Economic Valuation and Marketing",
        "Economic Analysis and Community Development",
        "Laboratory Services",
        "Maritime Services",
        "Finance and Accounting",
        "Human Resource Management and Administration",
        "Information Science",
        "Engineering and Maintenance",
        "Corporate Communication and Public Relations",
        "Strategy and Planning",
        "Performance Management, Monitoring and Evaluation",
        "Information Communication Technology (ICT)",
        "Partnership Development and Resource Mobilization",
        "Technical Capacity Building",
        "Quality Assurance and Compliance",
        "Business Development",
        "Corporation Secretary and Legal Services",
        "Internal Audit",
        "Supply Chain Management",
        "Research Centres"
    ],
    availableSupervisors: [
        "Edna N. Onkundi",
        "Polycarp Atunga",
        "Samuel Agwata",
        "Faith Gwanda",
        "Leonard Opasanjo",
        "Peter Mutuku",
        "Lawrence Bruce Owili",
    ],
    colorPalette: {
        deepNavy: '#0A3D62',
        oceanBlue: '#005B96',
        marineBlue: '#1a237e',
        aquaVibrant: '#00e5ff',
        cyanFresh: '#368DC5',
        skyBlue: '#87CEEB',
        coralSunset: '#FF6F61',
        warmSand: '#FFB400',
        seafoamGreen: '#48C9B0',
        cloudWhite: '#f8fafd',
        softGray: '#E8EEF7',
        charcoal: '#424242',
        oceanGradient: 'linear-gradient(135deg, #0A3D62 0%, #005B96 50%, #1B4F72 100%)',
        sunsetGradient: 'linear-gradient(135deg, #FF6F61 0%, #FFB400 100%)',
        freshGradient: 'linear-gradient(135deg, #00e5ff 0%, #48C9B0 100%)',


    },

    AvailableStations: [
        // { name: 'MOMBASA CENTRE', lat: -4.03951, lng: 39.6260 },
        { name: 'MOMBASA CENTRE', lat: -4.0546356, lng: 39.6826 },
        { name: 'SHIMONI STATION', lat: -4.0546356, lng: 39.6826 },
        { name: 'KISUMU CENTRE', lat: -0.059149, lng: 34.8066 },
        { name: 'KEGATI STATION', lat: -0.644496, lng: 34.7481 },
        { name: 'KALOKOL STATION', lat: 3.08222, lng: 36.0749 },
        { name: 'NAIROBI STATION', lat: -1.24936, lng: 36.7968 },
        { name: 'NAIVASHA STATION', lat: -0.664008, lng: 36.4651 },
        { name: 'BARINGO STATION', lat: 0.604245, lng: 35.9773 },
        { name: 'SANGORO STATION', lat: -0.394861, lng: 34.7374 },
        { name: 'SAGANA STATION', lat: -0.669415, lng: 37.2061 },
    ],
    genders: [
        'Male',
        'Female',
        'Other'
    ],

    REASONS: ["Sickness", "Fieldwork", "Research", "Workshop", "Official Assignment", "Remote Work"],
    LEAVE_TYPES: ["Adoption Leave", "Annual Leave", "Compassionate Leave", "Paternity Leave", "Sick Leave", "Study Leave", "Terminal Leave"],

}

export default coreDataDetails